//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderDll.VCService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VlcOrderData", Namespace="http://schemas.datacontract.org/2004/07/ValueCardDll")]
    [System.SerializableAttribute()]
    public partial class VlcOrderData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountPaidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtClientEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemberIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrganizationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PromoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityOrderedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double AmountPaid {
            get {
                return this.AmountPaidField;
            }
            set {
                if ((this.AmountPaidField.Equals(value) != true)) {
                    this.AmountPaidField = value;
                    this.RaisePropertyChanged("AmountPaid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtClientEmail {
            get {
                return this.ExtClientEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtClientEmailField, value) != true)) {
                    this.ExtClientEmailField = value;
                    this.RaisePropertyChanged("ExtClientEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MemberIDField, value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrganizationID {
            get {
                return this.OrganizationIDField;
            }
            set {
                if ((this.OrganizationIDField.Equals(value) != true)) {
                    this.OrganizationIDField = value;
                    this.RaisePropertyChanged("OrganizationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PromoID {
            get {
                return this.PromoIDField;
            }
            set {
                if ((this.PromoIDField.Equals(value) != true)) {
                    this.PromoIDField = value;
                    this.RaisePropertyChanged("PromoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantityOrdered {
            get {
                return this.QuantityOrderedField;
            }
            set {
                if ((this.QuantityOrderedField.Equals(value) != true)) {
                    this.QuantityOrderedField = value;
                    this.RaisePropertyChanged("QuantityOrdered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VCService.IValueCard")]
    public interface IValueCard {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValueCard/VlcInsertOrder", ReplyAction="http://tempuri.org/IValueCard/VlcInsertOrderResponse")]
        long VlcInsertOrder(OrderDll.VCService.VlcOrderData prop);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValueCard/VlcCancelOrder", ReplyAction="http://tempuri.org/IValueCard/VlcCancelOrderResponse")]
        long VlcCancelOrder(long valueCardTID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValueCard/VlcChangeCardNumber", ReplyAction="http://tempuri.org/IValueCard/VlcChangeCardNumberResponse")]
        long VlcChangeCardNumber(long valueCardTID, string newCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValueCard/VlcDeActivateOrder", ReplyAction="http://tempuri.org/IValueCard/VlcDeActivateOrderResponse")]
        long VlcDeActivateOrder(long valueCardTID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValueCard/VlcActivateOrder", ReplyAction="http://tempuri.org/IValueCard/VlcActivateOrderResponse")]
        long VlcActivateOrder(long valueCardTID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValueCardChannel : OrderDll.VCService.IValueCard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValueCardClient : System.ServiceModel.ClientBase<OrderDll.VCService.IValueCard>, OrderDll.VCService.IValueCard {
        
        public ValueCardClient() {
        }
        
        public ValueCardClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValueCardClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValueCardClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValueCardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long VlcInsertOrder(OrderDll.VCService.VlcOrderData prop) {
            return base.Channel.VlcInsertOrder(prop);
        }
        
        public long VlcCancelOrder(long valueCardTID) {
            return base.Channel.VlcCancelOrder(valueCardTID);
        }
        
        public long VlcChangeCardNumber(long valueCardTID, string newCardNumber) {
            return base.Channel.VlcChangeCardNumber(valueCardTID, newCardNumber);
        }
        
        public long VlcDeActivateOrder(long valueCardTID) {
            return base.Channel.VlcDeActivateOrder(valueCardTID);
        }
        
        public long VlcActivateOrder(long valueCardTID) {
            return base.Channel.VlcActivateOrder(valueCardTID);
        }
    }
}
