<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <LangVersion>7.1</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
    <Compile Remove="Configuration\ConfiguratiomnManager.cs" />
    <Compile Remove="EF\ContextFactory.cs" />
    <Compile Remove="EF\IClubContextFactory.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Communication\" />
    <Folder Include="Base\" />
    <Folder Include="EF\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Autofac" Version="4.9.1" />
    <PackageReference Include="Autofac.Configuration" Version="4.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.4.0" />
    <PackageReference Include="DtsLoggger" Version="2.0.3" />
    <PackageReference Include="Google.Apis" Version="1.38.2" />
    <PackageReference Include="Google.Apis.Auth" Version="1.38.2" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.38.0.1543" />
    <PackageReference Include="Google.Apis.Plus.v1" Version="1.38.0.1541" />
    <PackageReference Include="Google.Apis.ServiceUser.v1" Version="1.36.0.1373" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.4" />
    <PackageReference Include="Microsoft.AspNet.WebApi" Version="5.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.1.34" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="NLog.Extensions.Logging" Version="1.4.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.8.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Swashbuckle" Version="5.6.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="7.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Runtime.Caching" Version="4.5.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.1" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nofshonit.Logs\Nofshonit.Logs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Mvc.Core">
      <HintPath>..\..\..\..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.mvc.core\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Mvc.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.IdentityModel.Protocols">
      <HintPath>..\..\..\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.identitymodel.protocols\5.3.0\lib\netstandard2.0\Microsoft.IdentityModel.Protocols.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
