//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OrderDll.StockManage {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStockResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTotalBuyPerDayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataFromMemeoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDataMemeoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearMemoryCacheOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::OrderDll.Properties.Settings.Default.OrderDll_StockManage_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStockResponseCompletedEventHandler GetStockResponseCompleted;
        
        /// <remarks/>
        public event GetTotalBuyPerDayCompletedEventHandler GetTotalBuyPerDayCompleted;
        
        /// <remarks/>
        public event GetDataFromMemeoryCompletedEventHandler GetDataFromMemeoryCompleted;
        
        /// <remarks/>
        public event SetDataMemeoryCompletedEventHandler SetDataMemeoryCompleted;
        
        /// <remarks/>
        public event ClearMemoryCacheCompletedEventHandler ClearMemoryCacheCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockResponse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VariantStockResult[] GetStockResponse(VariantStock[] lstStocks, string dBname, int orgId) {
            object[] results = this.Invoke("GetStockResponse", new object[] {
                        lstStocks,
                        dBname,
                        orgId});
            return ((VariantStockResult[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockResponseAsync(VariantStock[] lstStocks, string dBname, int orgId) {
            this.GetStockResponseAsync(lstStocks, dBname, orgId, null);
        }
        
        /// <remarks/>
        public void GetStockResponseAsync(VariantStock[] lstStocks, string dBname, int orgId, object userState) {
            if ((this.GetStockResponseOperationCompleted == null)) {
                this.GetStockResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockResponseOperationCompleted);
            }
            this.InvokeAsync("GetStockResponse", new object[] {
                        lstStocks,
                        dBname,
                        orgId}, this.GetStockResponseOperationCompleted, userState);
        }
        
        private void OnGetStockResponseOperationCompleted(object arg) {
            if ((this.GetStockResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockResponseCompleted(this, new GetStockResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTotalBuyPerDay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetTotalBuyPerDay(System.DateTime dtCheck, string dBname, int orgId, long stockId) {
            object[] results = this.Invoke("GetTotalBuyPerDay", new object[] {
                        dtCheck,
                        dBname,
                        orgId,
                        stockId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetTotalBuyPerDayAsync(System.DateTime dtCheck, string dBname, int orgId, long stockId) {
            this.GetTotalBuyPerDayAsync(dtCheck, dBname, orgId, stockId, null);
        }
        
        /// <remarks/>
        public void GetTotalBuyPerDayAsync(System.DateTime dtCheck, string dBname, int orgId, long stockId, object userState) {
            if ((this.GetTotalBuyPerDayOperationCompleted == null)) {
                this.GetTotalBuyPerDayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTotalBuyPerDayOperationCompleted);
            }
            this.InvokeAsync("GetTotalBuyPerDay", new object[] {
                        dtCheck,
                        dBname,
                        orgId,
                        stockId}, this.GetTotalBuyPerDayOperationCompleted, userState);
        }
        
        private void OnGetTotalBuyPerDayOperationCompleted(object arg) {
            if ((this.GetTotalBuyPerDayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTotalBuyPerDayCompleted(this, new GetTotalBuyPerDayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataFromMemeory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetDataFromMemeory(int stockid) {
            object[] results = this.Invoke("GetDataFromMemeory", new object[] {
                        stockid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataFromMemeoryAsync(int stockid) {
            this.GetDataFromMemeoryAsync(stockid, null);
        }
        
        /// <remarks/>
        public void GetDataFromMemeoryAsync(int stockid, object userState) {
            if ((this.GetDataFromMemeoryOperationCompleted == null)) {
                this.GetDataFromMemeoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataFromMemeoryOperationCompleted);
            }
            this.InvokeAsync("GetDataFromMemeory", new object[] {
                        stockid}, this.GetDataFromMemeoryOperationCompleted, userState);
        }
        
        private void OnGetDataFromMemeoryOperationCompleted(object arg) {
            if ((this.GetDataFromMemeoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataFromMemeoryCompleted(this, new GetDataFromMemeoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetDataMemeory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetDataMemeory(string dBname, int orgId) {
            object[] results = this.Invoke("SetDataMemeory", new object[] {
                        dBname,
                        orgId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetDataMemeoryAsync(string dBname, int orgId) {
            this.SetDataMemeoryAsync(dBname, orgId, null);
        }
        
        /// <remarks/>
        public void SetDataMemeoryAsync(string dBname, int orgId, object userState) {
            if ((this.SetDataMemeoryOperationCompleted == null)) {
                this.SetDataMemeoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDataMemeoryOperationCompleted);
            }
            this.InvokeAsync("SetDataMemeory", new object[] {
                        dBname,
                        orgId}, this.SetDataMemeoryOperationCompleted, userState);
        }
        
        private void OnSetDataMemeoryOperationCompleted(object arg) {
            if ((this.SetDataMemeoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDataMemeoryCompleted(this, new SetDataMemeoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ClearMemoryCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearMemoryCache() {
            this.Invoke("ClearMemoryCache", new object[0]);
        }
        
        /// <remarks/>
        public void ClearMemoryCacheAsync() {
            this.ClearMemoryCacheAsync(null);
        }
        
        /// <remarks/>
        public void ClearMemoryCacheAsync(object userState) {
            if ((this.ClearMemoryCacheOperationCompleted == null)) {
                this.ClearMemoryCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearMemoryCacheOperationCompleted);
            }
            this.InvokeAsync("ClearMemoryCache", new object[0], this.ClearMemoryCacheOperationCompleted, userState);
        }
        
        private void OnClearMemoryCacheOperationCompleted(object arg) {
            if ((this.ClearMemoryCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearMemoryCacheCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VariantStock {
        
        private string fullBarCodeField;
        
        private int amountField;
        
        private bool isTradeField;
        
        /// <remarks/>
        public string FullBarCode {
            get {
                return this.fullBarCodeField;
            }
            set {
                this.fullBarCodeField = value;
            }
        }
        
        /// <remarks/>
        public int Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public bool IsTrade {
            get {
                return this.isTradeField;
            }
            set {
                this.isTradeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VariantStockResult {
        
        private string fullBarCodeField;
        
        private bool checkStockSeccsessField;
        
        /// <remarks/>
        public string FullBarCode {
            get {
                return this.fullBarCodeField;
            }
            set {
                this.fullBarCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool CheckStockSeccsess {
            get {
                return this.checkStockSeccsessField;
            }
            set {
                this.checkStockSeccsessField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetStockResponseCompletedEventHandler(object sender, GetStockResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariantStockResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariantStockResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetTotalBuyPerDayCompletedEventHandler(object sender, GetTotalBuyPerDayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTotalBuyPerDayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTotalBuyPerDayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetDataFromMemeoryCompletedEventHandler(object sender, GetDataFromMemeoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataFromMemeoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataFromMemeoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SetDataMemeoryCompletedEventHandler(object sender, SetDataMemeoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetDataMemeoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDataMemeoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ClearMemoryCacheCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591