//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeumiCardSvc
{
    using Nofshonit.Common;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StoreUserAnswer", Namespace="http://schemas.datacontract.org/2004/07/LCGWTest")]
    public partial class StoreUserAnswer : object
    {
        
        private System.Guid GuidField;
        
        private int RCField;
        
        private string RC_DESCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RC
        {
            get
            {
                return this.RCField;
            }
            set
            {
                this.RCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RC_DESC
        {
            get
            {
                return this.RC_DESCField;
            }
            set
            {
                this.RC_DESCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationAnswer", Namespace="http://schemas.datacontract.org/2004/07/LCGWTest")]
    public partial class AuthenticationAnswer : object
    {
        
        private int BenefitAmountField;
        
        private string Customer_NameField;
        
        private int Customer_TypeField;
        
        private string ID_typeField;
        
        private int RCField;
        
        private string RC_DESCField;
        
        private string TZField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BenefitAmount
        {
            get
            {
                return this.BenefitAmountField;
            }
            set
            {
                this.BenefitAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customer_Name
        {
            get
            {
                return this.Customer_NameField;
            }
            set
            {
                this.Customer_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Customer_Type
        {
            get
            {
                return this.Customer_TypeField;
            }
            set
            {
                this.Customer_TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_type
        {
            get
            {
                return this.ID_typeField;
            }
            set
            {
                this.ID_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RC
        {
            get
            {
                return this.RCField;
            }
            set
            {
                this.RCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RC_DESC
        {
            get
            {
                return this.RC_DESCField;
            }
            set
            {
                this.RC_DESCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TZ
        {
            get
            {
                return this.TZField;
            }
            set
            {
                this.TZField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerBuyExecuteAnswer", Namespace="http://schemas.datacontract.org/2004/07/LCGWTest")]
    public partial class CustomerBuyExecuteAnswer : object
    {
        
        private System.Collections.Generic.Dictionary<int, string> ClubsListField;
        
        private int RCField;
        
        private string RC_DESCField;
        
        private string TZField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> ClubsList
        {
            get
            {
                return this.ClubsListField;
            }
            set
            {
                this.ClubsListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RC
        {
            get
            {
                return this.RCField;
            }
            set
            {
                this.RCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RC_DESC
        {
            get
            {
                return this.RC_DESCField;
            }
            set
            {
                this.RC_DESCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TZ
        {
            get
            {
                return this.TZField;
            }
            set
            {
                this.TZField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeumiCardSvc.ILCBehatsdaa")]
    public interface ILCBehatsdaa
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCBehatsdaa/DoWork", ReplyAction="http://tempuri.org/ILCBehatsdaa/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCBehatsdaa/StoreUserDetails", ReplyAction="http://tempuri.org/ILCBehatsdaa/StoreUserDetailsResponse")]
        System.Threading.Tasks.Task<LeumiCardSvc.StoreUserAnswer> StoreUserDetailsAsync(int memberID, int benefitsUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCBehatsdaa/Authentication", ReplyAction="http://tempuri.org/ILCBehatsdaa/AuthenticationResponse")]
        System.Threading.Tasks.Task<LeumiCardSvc.AuthenticationAnswer> AuthenticationAsync(string TZ, string personalNumber, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILCBehatsdaa/CustomerBuyExecute", ReplyAction="http://tempuri.org/ILCBehatsdaa/CustomerBuyExecuteResponse")]
        System.Threading.Tasks.Task<LeumiCardSvc.CustomerBuyExecuteAnswer> CustomerBuyExecuteAsync(string cardNumber, string memberId, int organizationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ILCBehatsdaaChannel : LeumiCardSvc.ILCBehatsdaa, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class LCBehatsdaaClient : System.ServiceModel.ClientBase<LeumiCardSvc.ILCBehatsdaa>, LeumiCardSvc.ILCBehatsdaa
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LCBehatsdaaClient() : 
                base(LCBehatsdaaClient.GetDefaultBinding(), LCBehatsdaaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ILCBehatsdaa.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LCBehatsdaaClient(EndpointConfiguration endpointConfiguration) : 
                base(LCBehatsdaaClient.GetBindingForEndpoint(endpointConfiguration), LCBehatsdaaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LCBehatsdaaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LCBehatsdaaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LCBehatsdaaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LCBehatsdaaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LCBehatsdaaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync()
        {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Threading.Tasks.Task<LeumiCardSvc.StoreUserAnswer> StoreUserDetailsAsync(int memberID, int benefitsUsage)
        {
            return base.Channel.StoreUserDetailsAsync(memberID, benefitsUsage);
        }
        
        public System.Threading.Tasks.Task<LeumiCardSvc.AuthenticationAnswer> AuthenticationAsync(string TZ, string personalNumber, string type)
        {
            return base.Channel.AuthenticationAsync(TZ, personalNumber, type);
        }
        
        public System.Threading.Tasks.Task<LeumiCardSvc.CustomerBuyExecuteAnswer> CustomerBuyExecuteAsync(string cardNumber, string memberId, int organizationId)
        {
            return base.Channel.CustomerBuyExecuteAsync(cardNumber, memberId, organizationId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILCBehatsdaa))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ILCBehatsdaa))
            {
                return new System.ServiceModel.EndpointAddress(ConfigurationKey.GetValueFromConfigurations(ConfigurationKey.LeumiCard));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return LCBehatsdaaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ILCBehatsdaa);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return LCBehatsdaaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ILCBehatsdaa);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ILCBehatsdaa,
        }
    }
}
