//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OrderDll.TeleclalPayments {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DebitSoap", Namespace="http://www.telemessersms.co.il/webservice/")]
    public partial class Debit : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DebitCardFullOperationCompleted;
        
        private System.Threading.SendOrPostCallback DebitCardFullDebitCreditOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Debit() {
            this.Url = global::OrderDll.Properties.Settings.Default.OrderDll_TeleclalPayments_Debit;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DebitCardFullCompletedEventHandler DebitCardFullCompleted;
        
        /// <remarks/>
        public event DebitCardFullDebitCreditCompletedEventHandler DebitCardFullDebitCreditCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.telemessersms.co.il/webservice/DebitCardFull", RequestNamespace="http://www.telemessersms.co.il/webservice/", ResponseNamespace="http://www.telemessersms.co.il/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DebitCardFull(string UserName, string Password, string CreditCardNumber, string CVV, string ExpireDate, float TotalPay, int NumOfPayment, float FirstPayment, float EachPayment, int TransctionType, int CreditTerms, float StarsAmount, string ID, string Phone, bool CheckID) {
            object[] results = this.Invoke("DebitCardFull", new object[] {
                        UserName,
                        Password,
                        CreditCardNumber,
                        CVV,
                        ExpireDate,
                        TotalPay,
                        NumOfPayment,
                        FirstPayment,
                        EachPayment,
                        TransctionType,
                        CreditTerms,
                        StarsAmount,
                        ID,
                        Phone,
                        CheckID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DebitCardFullAsync(string UserName, string Password, string CreditCardNumber, string CVV, string ExpireDate, float TotalPay, int NumOfPayment, float FirstPayment, float EachPayment, int TransctionType, int CreditTerms, float StarsAmount, string ID, string Phone, bool CheckID) {
            this.DebitCardFullAsync(UserName, Password, CreditCardNumber, CVV, ExpireDate, TotalPay, NumOfPayment, FirstPayment, EachPayment, TransctionType, CreditTerms, StarsAmount, ID, Phone, CheckID, null);
        }
        
        /// <remarks/>
        public void DebitCardFullAsync(
                    string UserName, 
                    string Password, 
                    string CreditCardNumber, 
                    string CVV, 
                    string ExpireDate, 
                    float TotalPay, 
                    int NumOfPayment, 
                    float FirstPayment, 
                    float EachPayment, 
                    int TransctionType, 
                    int CreditTerms, 
                    float StarsAmount, 
                    string ID, 
                    string Phone, 
                    bool CheckID, 
                    object userState) {
            if ((this.DebitCardFullOperationCompleted == null)) {
                this.DebitCardFullOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDebitCardFullOperationCompleted);
            }
            this.InvokeAsync("DebitCardFull", new object[] {
                        UserName,
                        Password,
                        CreditCardNumber,
                        CVV,
                        ExpireDate,
                        TotalPay,
                        NumOfPayment,
                        FirstPayment,
                        EachPayment,
                        TransctionType,
                        CreditTerms,
                        StarsAmount,
                        ID,
                        Phone,
                        CheckID}, this.DebitCardFullOperationCompleted, userState);
        }
        
        private void OnDebitCardFullOperationCompleted(object arg) {
            if ((this.DebitCardFullCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DebitCardFullCompleted(this, new DebitCardFullCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.telemessersms.co.il/webservice/DebitCardFullDebitCredit", RequestNamespace="http://www.telemessersms.co.il/webservice/", ResponseNamespace="http://www.telemessersms.co.il/webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DebitCardFullDebitCredit(
                    string UserName, 
                    string Password, 
                    string CreditCardNumber, 
                    string CVV, 
                    string ExpireDate, 
                    float TotalPay, 
                    int NumOfPayment, 
                    float FirstPayment, 
                    float EachPayment, 
                    int TransctionType, 
                    int CreditTerms, 
                    float StarsAmount, 
                    string ID, 
                    string Phone, 
                    bool CheckID, 
                    string DebitCredit) {
            object[] results = this.Invoke("DebitCardFullDebitCredit", new object[] {
                        UserName,
                        Password,
                        CreditCardNumber,
                        CVV,
                        ExpireDate,
                        TotalPay,
                        NumOfPayment,
                        FirstPayment,
                        EachPayment,
                        TransctionType,
                        CreditTerms,
                        StarsAmount,
                        ID,
                        Phone,
                        CheckID,
                        DebitCredit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DebitCardFullDebitCreditAsync(
                    string UserName, 
                    string Password, 
                    string CreditCardNumber, 
                    string CVV, 
                    string ExpireDate, 
                    float TotalPay, 
                    int NumOfPayment, 
                    float FirstPayment, 
                    float EachPayment, 
                    int TransctionType, 
                    int CreditTerms, 
                    float StarsAmount, 
                    string ID, 
                    string Phone, 
                    bool CheckID, 
                    string DebitCredit) {
            this.DebitCardFullDebitCreditAsync(UserName, Password, CreditCardNumber, CVV, ExpireDate, TotalPay, NumOfPayment, FirstPayment, EachPayment, TransctionType, CreditTerms, StarsAmount, ID, Phone, CheckID, DebitCredit, null);
        }
        
        /// <remarks/>
        public void DebitCardFullDebitCreditAsync(
                    string UserName, 
                    string Password, 
                    string CreditCardNumber, 
                    string CVV, 
                    string ExpireDate, 
                    float TotalPay, 
                    int NumOfPayment, 
                    float FirstPayment, 
                    float EachPayment, 
                    int TransctionType, 
                    int CreditTerms, 
                    float StarsAmount, 
                    string ID, 
                    string Phone, 
                    bool CheckID, 
                    string DebitCredit, 
                    object userState) {
            if ((this.DebitCardFullDebitCreditOperationCompleted == null)) {
                this.DebitCardFullDebitCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDebitCardFullDebitCreditOperationCompleted);
            }
            this.InvokeAsync("DebitCardFullDebitCredit", new object[] {
                        UserName,
                        Password,
                        CreditCardNumber,
                        CVV,
                        ExpireDate,
                        TotalPay,
                        NumOfPayment,
                        FirstPayment,
                        EachPayment,
                        TransctionType,
                        CreditTerms,
                        StarsAmount,
                        ID,
                        Phone,
                        CheckID,
                        DebitCredit}, this.DebitCardFullDebitCreditOperationCompleted, userState);
        }
        
        private void OnDebitCardFullDebitCreditOperationCompleted(object arg) {
            if ((this.DebitCardFullDebitCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DebitCardFullDebitCreditCompleted(this, new DebitCardFullDebitCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DebitCardFullCompletedEventHandler(object sender, DebitCardFullCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DebitCardFullCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DebitCardFullCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void DebitCardFullDebitCreditCompletedEventHandler(object sender, DebitCardFullDebitCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DebitCardFullDebitCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DebitCardFullDebitCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591