//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDataService
{
    using Nofshonit.Common;
    using System.ComponentModel;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.ArithmeticOperations))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.Card_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.SingelChargeDischargeRequest_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.ManualOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.Swap_Cards))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.Club_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.CardSequentialNum_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.SequentialNumChargeDischargeRequest_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.TransferAmountBetweenCardsRequest_DTS))]
    public partial class BaseRequest_DTS : object
    {
        
        private int OrganizationIDField;
        
        private long OriginalRequestField;
        
        private string OriginalRequestDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrganizationID
        {
            get
            {
                return this.OrganizationIDField;
            }
            set
            {
                this.OrganizationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OriginalRequest
        {
            get
            {
                return this.OriginalRequestField;
            }
            set
            {
                this.OriginalRequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalRequestDescription
        {
            get
            {
                return this.OriginalRequestDescriptionField;
            }
            set
            {
                this.OriginalRequestDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArithmeticOperations", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.Card_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.SingelChargeDischargeRequest_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.ManualOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.Swap_Cards))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.Club_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.CardSequentialNum_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.SequentialNumChargeDischargeRequest_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.TransferAmountBetweenCardsRequest_DTS))]
    public partial class ArithmeticOperations : OnlineDataService.BaseRequest_DTS
    {
        
        private string TerminalUniqueIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminalUniqueId
        {
            get
            {
                return this.TerminalUniqueIdField;
            }
            set
            {
                this.TerminalUniqueIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Card_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.SingelChargeDischargeRequest_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.ManualOperation))]
    public partial class Card_DTS : OnlineDataService.ArithmeticOperations
    {
        
        private string CardNumberField;
        
        private short CvvField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cvv
        {
            get
            {
                return this.CvvField;
            }
            set
            {
                this.CvvField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingelChargeDischargeRequest_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class SingelChargeDischargeRequest_DTS : OnlineDataService.Card_DTS
    {
        
        private OnlineDataService.ChargeDischarge chargeDischargeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ChargeDischarge chargeDischarge
        {
            get
            {
                return this.chargeDischargeField;
            }
            set
            {
                this.chargeDischargeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManualOperation", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class ManualOperation : OnlineDataService.Card_DTS
    {
        
        private decimal AmountField;
        
        private string CancelledInvoiceNumberField;
        
        private long CancelledTransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CancelledInvoiceNumber
        {
            get
            {
                return this.CancelledInvoiceNumberField;
            }
            set
            {
                this.CancelledInvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CancelledTransactionId
        {
            get
            {
                return this.CancelledTransactionIdField;
            }
            set
            {
                this.CancelledTransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Swap_Cards", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class Swap_Cards : OnlineDataService.ArithmeticOperations
    {
        
        private long CardNumberFromField;
        
        private long CardNumberToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardNumberFrom
        {
            get
            {
                return this.CardNumberFromField;
            }
            set
            {
                this.CardNumberFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CardNumberTo
        {
            get
            {
                return this.CardNumberToField;
            }
            set
            {
                this.CardNumberToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Club_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.CardSequentialNum_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.SequentialNumChargeDischargeRequest_DTS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.TransferAmountBetweenCardsRequest_DTS))]
    public partial class Club_DTS : OnlineDataService.ArithmeticOperations
    {
        
        private int VerIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VerID
        {
            get
            {
                return this.VerIDField;
            }
            set
            {
                this.VerIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardSequentialNum_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OnlineDataService.SequentialNumChargeDischargeRequest_DTS))]
    public partial class CardSequentialNum_DTS : OnlineDataService.Club_DTS
    {
        
        private int SequentialNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequentialNum
        {
            get
            {
                return this.SequentialNumField;
            }
            set
            {
                this.SequentialNumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SequentialNumChargeDischargeRequest_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class SequentialNumChargeDischargeRequest_DTS : OnlineDataService.CardSequentialNum_DTS
    {
        
        private OnlineDataService.ChargeDischarge chargeDischargeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ChargeDischarge chargeDischarge
        {
            get
            {
                return this.chargeDischargeField;
            }
            set
            {
                this.chargeDischargeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferAmountBetweenCardsRequest_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class TransferAmountBetweenCardsRequest_DTS : OnlineDataService.Club_DTS
    {
        
        private decimal AmountField;
        
        private string FromCardNumberField;
        
        private string FromFullNameField;
        
        private string FromPhoneNumberField;
        
        private string ToCardNumberField;
        
        private string ToFullNameField;
        
        private string ToPhoneNumberField;
        
        private int WalletIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCardNumber
        {
            get
            {
                return this.FromCardNumberField;
            }
            set
            {
                this.FromCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromFullName
        {
            get
            {
                return this.FromFullNameField;
            }
            set
            {
                this.FromFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPhoneNumber
        {
            get
            {
                return this.FromPhoneNumberField;
            }
            set
            {
                this.FromPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCardNumber
        {
            get
            {
                return this.ToCardNumberField;
            }
            set
            {
                this.ToCardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToFullName
        {
            get
            {
                return this.ToFullNameField;
            }
            set
            {
                this.ToFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhoneNumber
        {
            get
            {
                return this.ToPhoneNumberField;
            }
            set
            {
                this.ToPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WalletID
        {
            get
            {
                return this.WalletIDField;
            }
            set
            {
                this.WalletIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChargeDischarge", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class ChargeDischarge : object
    {
        
        private decimal AmountField;
        
        private int WalletIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WalletID
        {
            get
            {
                return this.WalletIDField;
            }
            set
            {
                this.WalletIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse_DTSOfReponseStatuses_DTSkQ_SBiMqu", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class ServiceResponse_DTSOfReponseStatuses_DTSkQ_SBiMqu : object
    {
        
        private OnlineDataService.ReponseStatuses_DTS[] BodyField;
        
        private int ErroreCodeField;
        
        private string ErroreMessageField;
        
        private string InvoiceNumberField;
        
        private OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTSField;
        
        private long TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ReponseStatuses_DTS[] Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErroreCode
        {
            get
            {
                return this.ErroreCodeField;
            }
            set
            {
                this.ErroreCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroreMessage
        {
            get
            {
                return this.ErroreMessageField;
            }
            set
            {
                this.ErroreMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTS
        {
            get
            {
                return this.ResponseStatus_DTSField;
            }
            set
            {
                this.ResponseStatus_DTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReponseStatuses_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public enum ReponseStatuses_DTS : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succeeded = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartiallySucceeded = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unavailable = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAllowed = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu : object
    {
        
        private OnlineDataService.WalletModel_DTS[] BodyField;
        
        private int ErroreCodeField;
        
        private string ErroreMessageField;
        
        private string InvoiceNumberField;
        
        private OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTSField;
        
        private long TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.WalletModel_DTS[] Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErroreCode
        {
            get
            {
                return this.ErroreCodeField;
            }
            set
            {
                this.ErroreCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroreMessage
        {
            get
            {
                return this.ErroreMessageField;
            }
            set
            {
                this.ErroreMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTS
        {
            get
            {
                return this.ResponseStatus_DTSField;
            }
            set
            {
                this.ResponseStatus_DTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WalletModel_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class WalletModel_DTS : object
    {
        
        private decimal BalanceField;
        
        private int IdField;
        
        private string NameField;
        
        private string ValidFromField;
        
        private string ValidThruField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidFrom
        {
            get
            {
                return this.ValidFromField;
            }
            set
            {
                this.ValidFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidThru
        {
            get
            {
                return this.ValidThruField;
            }
            set
            {
                this.ValidThruField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardActivitiesReq_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class CardActivitiesReq_DTS : object
    {
        
        private string CardNumberField;
        
        private int CvvField;
        
        private System.DateTime DateFromField;
        
        private System.DateTime DateToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cvv
        {
            get
            {
                return this.CvvField;
            }
            set
            {
                this.CvvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateFrom
        {
            get
            {
                return this.DateFromField;
            }
            set
            {
                this.DateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTo
        {
            get
            {
                return this.DateToField;
            }
            set
            {
                this.DateToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse_DTSOfCardActivity_DTSkQ_SBiMqu", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class ServiceResponse_DTSOfCardActivity_DTSkQ_SBiMqu : object
    {
        
        private OnlineDataService.CardActivity_DTS[] BodyField;
        
        private int ErroreCodeField;
        
        private string ErroreMessageField;
        
        private string InvoiceNumberField;
        
        private OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTSField;
        
        private long TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.CardActivity_DTS[] Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErroreCode
        {
            get
            {
                return this.ErroreCodeField;
            }
            set
            {
                this.ErroreCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroreMessage
        {
            get
            {
                return this.ErroreMessageField;
            }
            set
            {
                this.ErroreMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTS
        {
            get
            {
                return this.ResponseStatus_DTSField;
            }
            set
            {
                this.ResponseStatus_DTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardActivity_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class CardActivity_DTS : object
    {
        
        private decimal AmountField;
        
        private string ChainNameField;
        
        private string InvoiceNumberField;
        
        private string NameField;
        
        private int ParentChainIDField;
        
        private System.DateTime actionDateField;
        
        private long activityIDField;
        
        private string activityType_DTSField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChainName
        {
            get
            {
                return this.ChainNameField;
            }
            set
            {
                this.ChainNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentChainID
        {
            get
            {
                return this.ParentChainIDField;
            }
            set
            {
                this.ParentChainIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime actionDate
        {
            get
            {
                return this.actionDateField;
            }
            set
            {
                this.actionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long activityID
        {
            get
            {
                return this.activityIDField;
            }
            set
            {
                this.activityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string activityType_DTS
        {
            get
            {
                return this.activityType_DTSField;
            }
            set
            {
                this.activityType_DTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class Response_DTS : object
    {
        
        private OnlineDataService.AccountDischarges_DTS[] AccountDischarges_DTSField;
        
        private int AmountOfReservedCardsField;
        
        private string ErrorField;
        
        private string FileUrlField;
        
        private string FriendlyMessageField;
        
        private OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.AccountDischarges_DTS[] AccountDischarges_DTS
        {
            get
            {
                return this.AccountDischarges_DTSField;
            }
            set
            {
                this.AccountDischarges_DTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AmountOfReservedCards
        {
            get
            {
                return this.AmountOfReservedCardsField;
            }
            set
            {
                this.AmountOfReservedCardsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileUrl
        {
            get
            {
                return this.FileUrlField;
            }
            set
            {
                this.FileUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyMessage
        {
            get
            {
                return this.FriendlyMessageField;
            }
            set
            {
                this.FriendlyMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTS
        {
            get
            {
                return this.ResponseStatus_DTSField;
            }
            set
            {
                this.ResponseStatus_DTSField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDischarges_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class AccountDischarges_DTS : object
    {
        
        private decimal AmountDischargedField;
        
        private int WalletIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmountDischarged
        {
            get
            {
                return this.AmountDischargedField;
            }
            set
            {
                this.AmountDischargedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WalletID
        {
            get
            {
                return this.WalletIDField;
            }
            set
            {
                this.WalletIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceResponse_DTSOfDischargeModel_DTSkQ_SBiMqu", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class ServiceResponse_DTSOfDischargeModel_DTSkQ_SBiMqu : object
    {
        
        private OnlineDataService.DischargeModel_DTS[] BodyField;
        
        private int ErroreCodeField;
        
        private string ErroreMessageField;
        
        private string InvoiceNumberField;
        
        private OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTSField;
        
        private long TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.DischargeModel_DTS[] Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErroreCode
        {
            get
            {
                return this.ErroreCodeField;
            }
            set
            {
                this.ErroreCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErroreMessage
        {
            get
            {
                return this.ErroreMessageField;
            }
            set
            {
                this.ErroreMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.ReponseStatuses_DTS ResponseStatus_DTS
        {
            get
            {
                return this.ResponseStatus_DTSField;
            }
            set
            {
                this.ResponseStatus_DTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DischargeModel_DTS", Namespace="http://schemas.datacontract.org/2004/07/VpayDll")]
    public partial class DischargeModel_DTS : object
    {
        
        private string ErrorField;
        
        private int ErrorCodeField;
        
        private bool HasSucceededField;
        
        private OnlineDataService.AccountDischarges_DTS[] accountDischarges_DTSField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasSucceeded
        {
            get
            {
                return this.HasSucceededField;
            }
            set
            {
                this.HasSucceededField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineDataService.AccountDischarges_DTS[] accountDischarges_DTS
        {
            get
            {
                return this.accountDischarges_DTSField;
            }
            set
            {
                this.accountDischarges_DTSField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineDataService.IOnLineData")]
    public interface IOnLineData
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/Moshe", ReplyAction="http://tempuri.org/IOnLineData/MosheResponse")]
        System.Threading.Tasks.Task<OnlineDataService.MosheResponse> MosheAsync(OnlineDataService.MosheRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/TransferAmountBetweenCardsDts", ReplyAction="http://tempuri.org/IOnLineData/TransferAmountBetweenCardsDtsResponse")]
        System.Threading.Tasks.Task<OnlineDataService.TransferAmountBetweenCardsDtsResponse> TransferAmountBetweenCardsDtsAsync(OnlineDataService.TransferAmountBetweenCardsDtsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/GetCardBalance_DTS", ReplyAction="http://tempuri.org/IOnLineData/GetCardBalance_DTSResponse")]
        System.Threading.Tasks.Task<OnlineDataService.GetCardBalance_DTSResponse> GetCardBalance_DTSAsync(OnlineDataService.GetCardBalance_DTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/GetCardActivities_DTS", ReplyAction="http://tempuri.org/IOnLineData/GetCardActivities_DTSResponse")]
        System.Threading.Tasks.Task<OnlineDataService.GetCardActivities_DTSResponse> GetCardActivities_DTSAsync(OnlineDataService.GetCardActivities_DTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/SingelDeposit", ReplyAction="http://tempuri.org/IOnLineData/SingelDepositResponse")]
        System.Threading.Tasks.Task<OnlineDataService.SingelDepositResponse> SingelDepositAsync(OnlineDataService.SingelDepositRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/SingelActivateCard", ReplyAction="http://tempuri.org/IOnLineData/SingelActivateCardResponse")]
        System.Threading.Tasks.Task<OnlineDataService.SingelActivateCardResponse> SingelActivateCardAsync(OnlineDataService.SingelActivateCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/SingelBlockCard", ReplyAction="http://tempuri.org/IOnLineData/SingelBlockCardResponse")]
        System.Threading.Tasks.Task<OnlineDataService.SingelBlockCardResponse> SingelBlockCardAsync(OnlineDataService.SingelBlockCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/CardsSwap_DTS", ReplyAction="http://tempuri.org/IOnLineData/CardsSwap_DTSResponse")]
        System.Threading.Tasks.Task<OnlineDataService.CardsSwap_DTSResponse> CardsSwap_DTSAsync(OnlineDataService.CardsSwap_DTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/SingelUnBlockCard", ReplyAction="http://tempuri.org/IOnLineData/SingelUnBlockCardResponse")]
        System.Threading.Tasks.Task<OnlineDataService.SingelUnBlockCardResponse> SingelUnBlockCardAsync(OnlineDataService.SingelUnBlockCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/ManualCancelWithrawDeposit_DTS", ReplyAction="http://tempuri.org/IOnLineData/ManualCancelWithrawDeposit_DTSResponse")]
        System.Threading.Tasks.Task<OnlineDataService.ManualCancelWithrawDeposit_DTSResponse> ManualCancelWithrawDeposit_DTSAsync(OnlineDataService.ManualCancelWithrawDeposit_DTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/ManualWithrawDeposit_DTS", ReplyAction="http://tempuri.org/IOnLineData/ManualWithrawDeposit_DTSResponse")]
        System.Threading.Tasks.Task<OnlineDataService.ManualWithrawDeposit_DTSResponse> ManualWithrawDeposit_DTSAsync(OnlineDataService.ManualWithrawDeposit_DTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/ManualCancelDeposit_DTS", ReplyAction="http://tempuri.org/IOnLineData/ManualCancelDeposit_DTSResponse")]
        System.Threading.Tasks.Task<OnlineDataService.ManualCancelDeposit_DTSResponse> ManualCancelDeposit_DTSAsync(OnlineDataService.ManualCancelDeposit_DTSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOnLineData/SingelPartialDischarge", ReplyAction="http://tempuri.org/IOnLineData/SingelPartialDischargeResponse")]
        System.Threading.Tasks.Task<OnlineDataService.SingelPartialDischargeResponse> SingelPartialDischargeAsync(OnlineDataService.SingelPartialDischargeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Moshe", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MosheRequest
    {
        
        public MosheRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MosheResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MosheResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MosheResult;
        
        public MosheResponse()
        {
        }
        
        public MosheResponse(string MosheResult)
        {
            this.MosheResult = MosheResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferAmountBetweenCardsDts", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TransferAmountBetweenCardsDtsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.TransferAmountBetweenCardsRequest_DTS request;
        
        public TransferAmountBetweenCardsDtsRequest()
        {
        }
        
        public TransferAmountBetweenCardsDtsRequest(OnlineDataService.TransferAmountBetweenCardsRequest_DTS request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TransferAmountBetweenCardsDtsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TransferAmountBetweenCardsDtsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfReponseStatuses_DTSkQ_SBiMqu TransferAmountBetweenCardsDtsResult;
        
        public TransferAmountBetweenCardsDtsResponse()
        {
        }
        
        public TransferAmountBetweenCardsDtsResponse(OnlineDataService.ServiceResponse_DTSOfReponseStatuses_DTSkQ_SBiMqu TransferAmountBetweenCardsDtsResult)
        {
            this.TransferAmountBetweenCardsDtsResult = TransferAmountBetweenCardsDtsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardBalance_DTS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardBalance_DTSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.Card_DTS card;
        
        public GetCardBalance_DTSRequest()
        {
        }
        
        public GetCardBalance_DTSRequest(OnlineDataService.Card_DTS card)
        {
            this.card = card;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardBalance_DTSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardBalance_DTSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu GetCardBalance_DTSResult;
        
        public GetCardBalance_DTSResponse()
        {
        }
        
        public GetCardBalance_DTSResponse(OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu GetCardBalance_DTSResult)
        {
            this.GetCardBalance_DTSResult = GetCardBalance_DTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardActivities_DTS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardActivities_DTSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.CardActivitiesReq_DTS cardActivitiesReq_DTS;
        
        public GetCardActivities_DTSRequest()
        {
        }
        
        public GetCardActivities_DTSRequest(OnlineDataService.CardActivitiesReq_DTS cardActivitiesReq_DTS)
        {
            this.cardActivitiesReq_DTS = cardActivitiesReq_DTS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCardActivities_DTSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCardActivities_DTSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfCardActivity_DTSkQ_SBiMqu GetCardActivities_DTSResult;
        
        public GetCardActivities_DTSResponse()
        {
        }
        
        public GetCardActivities_DTSResponse(OnlineDataService.ServiceResponse_DTSOfCardActivity_DTSkQ_SBiMqu GetCardActivities_DTSResult)
        {
            this.GetCardActivities_DTSResult = GetCardActivities_DTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelDeposit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelDepositRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.SingelChargeDischargeRequest_DTS request;
        
        public SingelDepositRequest()
        {
        }
        
        public SingelDepositRequest(OnlineDataService.SingelChargeDischargeRequest_DTS request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelDepositResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelDepositResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu SingelDepositResult;
        
        public SingelDepositResponse()
        {
        }
        
        public SingelDepositResponse(OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu SingelDepositResult)
        {
            this.SingelDepositResult = SingelDepositResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelActivateCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelActivateCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.Card_DTS card;
        
        public SingelActivateCardRequest()
        {
        }
        
        public SingelActivateCardRequest(OnlineDataService.Card_DTS card)
        {
            this.card = card;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelActivateCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelActivateCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.Response_DTS SingelActivateCardResult;
        
        public SingelActivateCardResponse()
        {
        }
        
        public SingelActivateCardResponse(OnlineDataService.Response_DTS SingelActivateCardResult)
        {
            this.SingelActivateCardResult = SingelActivateCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelBlockCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelBlockCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.Card_DTS card;
        
        public SingelBlockCardRequest()
        {
        }
        
        public SingelBlockCardRequest(OnlineDataService.Card_DTS card)
        {
            this.card = card;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelBlockCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelBlockCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.Response_DTS SingelBlockCardResult;
        
        public SingelBlockCardResponse()
        {
        }
        
        public SingelBlockCardResponse(OnlineDataService.Response_DTS SingelBlockCardResult)
        {
            this.SingelBlockCardResult = SingelBlockCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CardsSwap_DTS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CardsSwap_DTSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.Swap_Cards request;
        
        public CardsSwap_DTSRequest()
        {
        }
        
        public CardsSwap_DTSRequest(OnlineDataService.Swap_Cards request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CardsSwap_DTSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CardsSwap_DTSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu CardsSwap_DTSResult;
        
        public CardsSwap_DTSResponse()
        {
        }
        
        public CardsSwap_DTSResponse(OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu CardsSwap_DTSResult)
        {
            this.CardsSwap_DTSResult = CardsSwap_DTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelUnBlockCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelUnBlockCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.CardSequentialNum_DTS request;
        
        public SingelUnBlockCardRequest()
        {
        }
        
        public SingelUnBlockCardRequest(OnlineDataService.CardSequentialNum_DTS request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelUnBlockCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelUnBlockCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.Response_DTS SingelUnBlockCardResult;
        
        public SingelUnBlockCardResponse()
        {
        }
        
        public SingelUnBlockCardResponse(OnlineDataService.Response_DTS SingelUnBlockCardResult)
        {
            this.SingelUnBlockCardResult = SingelUnBlockCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ManualCancelWithrawDeposit_DTS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ManualCancelWithrawDeposit_DTSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ManualOperation request;
        
        public ManualCancelWithrawDeposit_DTSRequest()
        {
        }
        
        public ManualCancelWithrawDeposit_DTSRequest(OnlineDataService.ManualOperation request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ManualCancelWithrawDeposit_DTSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ManualCancelWithrawDeposit_DTSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu ManualCancelWithrawDeposit_DTSResult;
        
        public ManualCancelWithrawDeposit_DTSResponse()
        {
        }
        
        public ManualCancelWithrawDeposit_DTSResponse(OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu ManualCancelWithrawDeposit_DTSResult)
        {
            this.ManualCancelWithrawDeposit_DTSResult = ManualCancelWithrawDeposit_DTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ManualWithrawDeposit_DTS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ManualWithrawDeposit_DTSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ManualOperation request;
        
        public ManualWithrawDeposit_DTSRequest()
        {
        }
        
        public ManualWithrawDeposit_DTSRequest(OnlineDataService.ManualOperation request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ManualWithrawDeposit_DTSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ManualWithrawDeposit_DTSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu ManualWithrawDeposit_DTSResult;
        
        public ManualWithrawDeposit_DTSResponse()
        {
        }
        
        public ManualWithrawDeposit_DTSResponse(OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu ManualWithrawDeposit_DTSResult)
        {
            this.ManualWithrawDeposit_DTSResult = ManualWithrawDeposit_DTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ManualCancelDeposit_DTS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ManualCancelDeposit_DTSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ManualOperation request;
        
        public ManualCancelDeposit_DTSRequest()
        {
        }
        
        public ManualCancelDeposit_DTSRequest(OnlineDataService.ManualOperation request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ManualCancelDeposit_DTSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ManualCancelDeposit_DTSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu ManualCancelDeposit_DTSResult;
        
        public ManualCancelDeposit_DTSResponse()
        {
        }
        
        public ManualCancelDeposit_DTSResponse(OnlineDataService.ServiceResponse_DTSOfWalletModel_DTSkQ_SBiMqu ManualCancelDeposit_DTSResult)
        {
            this.ManualCancelDeposit_DTSResult = ManualCancelDeposit_DTSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelPartialDischarge", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelPartialDischargeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.SequentialNumChargeDischargeRequest_DTS request;
        
        public SingelPartialDischargeRequest()
        {
        }
        
        public SingelPartialDischargeRequest(OnlineDataService.SequentialNumChargeDischargeRequest_DTS request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingelPartialDischargeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SingelPartialDischargeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public OnlineDataService.ServiceResponse_DTSOfDischargeModel_DTSkQ_SBiMqu SingelPartialDischargeResult;
        
        public SingelPartialDischargeResponse()
        {
        }
        
        public SingelPartialDischargeResponse(OnlineDataService.ServiceResponse_DTSOfDischargeModel_DTSkQ_SBiMqu SingelPartialDischargeResult)
        {
            this.SingelPartialDischargeResult = SingelPartialDischargeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IOnLineDataChannel : OnlineDataService.IOnLineData, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class OnLineDataClient : System.ServiceModel.ClientBase<OnlineDataService.IOnLineData>, OnlineDataService.IOnLineData
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OnLineDataClient() : 
                base(OnLineDataClient.GetDefaultBinding(), OnLineDataClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOnLineData.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnLineDataClient(EndpointConfiguration endpointConfiguration) : 
                base(OnLineDataClient.GetBindingForEndpoint(endpointConfiguration), OnLineDataClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnLineDataClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OnLineDataClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnLineDataClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OnLineDataClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OnLineDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.MosheResponse> MosheAsync(OnlineDataService.MosheRequest request)
        {
            return base.Channel.MosheAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.TransferAmountBetweenCardsDtsResponse> TransferAmountBetweenCardsDtsAsync(OnlineDataService.TransferAmountBetweenCardsDtsRequest request)
        {
            return base.Channel.TransferAmountBetweenCardsDtsAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.GetCardBalance_DTSResponse> GetCardBalance_DTSAsync(OnlineDataService.GetCardBalance_DTSRequest request)
        {
            return base.Channel.GetCardBalance_DTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.GetCardActivities_DTSResponse> GetCardActivities_DTSAsync(OnlineDataService.GetCardActivities_DTSRequest request)
        {
            return base.Channel.GetCardActivities_DTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.SingelDepositResponse> SingelDepositAsync(OnlineDataService.SingelDepositRequest request)
        {
            return base.Channel.SingelDepositAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.SingelActivateCardResponse> SingelActivateCardAsync(OnlineDataService.SingelActivateCardRequest request)
        {
            return base.Channel.SingelActivateCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.SingelBlockCardResponse> SingelBlockCardAsync(OnlineDataService.SingelBlockCardRequest request)
        {
            return base.Channel.SingelBlockCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.CardsSwap_DTSResponse> CardsSwap_DTSAsync(OnlineDataService.CardsSwap_DTSRequest request)
        {
            return base.Channel.CardsSwap_DTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.SingelUnBlockCardResponse> SingelUnBlockCardAsync(OnlineDataService.SingelUnBlockCardRequest request)
        {
            return base.Channel.SingelUnBlockCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.ManualCancelWithrawDeposit_DTSResponse> ManualCancelWithrawDeposit_DTSAsync(OnlineDataService.ManualCancelWithrawDeposit_DTSRequest request)
        {
            return base.Channel.ManualCancelWithrawDeposit_DTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.ManualWithrawDeposit_DTSResponse> ManualWithrawDeposit_DTSAsync(OnlineDataService.ManualWithrawDeposit_DTSRequest request)
        {
            return base.Channel.ManualWithrawDeposit_DTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.ManualCancelDeposit_DTSResponse> ManualCancelDeposit_DTSAsync(OnlineDataService.ManualCancelDeposit_DTSRequest request)
        {
            return base.Channel.ManualCancelDeposit_DTSAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineDataService.SingelPartialDischargeResponse> SingelPartialDischargeAsync(OnlineDataService.SingelPartialDischargeRequest request)
        {
            return base.Channel.SingelPartialDischargeAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnLineData))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOnLineData))
            {
                return new System.ServiceModel.EndpointAddress(ConfigurationKey.GetValueFromConfigurations(ConfigurationKey.VPayService)); //"http://172.29.90.16:85/OnLineData.svc"); //TODO: Need to change to prod
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OnLineDataClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOnLineData);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OnLineDataClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOnLineData);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOnLineData,
        }
    }
}
